kaaaaakun/ft_transcendence

docker-compose.yml

ボリューム名は各々で決めたいかもしれないのでコメントアウトしています

docker-composeのドラフトを作成

---

web/src/js/main.js

ひとまずトップページです。
buttonをした時って何を送ると都合がいいのか？
この辺、historyapiと関連してくるんですか？

Create top page

---

web/index.html
web/src/js/components/InputAlias.js
web/src/js/components/ui/button.js
web/src/js/main.js

とりあえず、index.htmlのスクリプト書き換えて、表示してみています。
ファイル作る場所とか、あってますか？

Create alias input page

---

api/conf/app_match/models.py
api/conf/app_player/models.py
api/conf/app_tournament/models.py
api/conf/project/urls.py

**Testの方法**
modelのテーブル名がDBと一致していること
uriがOpenAPIと一致していること
コンテナ内で3つのアプリのテストを実行して合格すること
**やったこと**
modelのテーブル名をDBと一致させた
uriをOpenAPIと一致させた
上記に関連してコードを置き換えた

Api align table name to db

---

api/README.md
api/conf/app_match/tests.py
api/conf/app_match/utils.py
api/conf/app_match/views.py
api/conf/app_tournament/tests.py
api/conf/app_tournament/utils.py
api/conf/app_tournament/views.py

**Testの方法**
- リクエスト、レスポンスの内容がopenAPIと一致していること
- test ~~がすべて成功すること
**やったこと**
リクエスト、レスポンスの内容をOpenAPIと一致させた
クッキーに対応したエンドポイントのメソッド追加
再利用しやすいコードへの変更
ReadMeの更新

Api align  IO data to open api

---

.gitignore
Makefile

**Testの方法**
- makeして、Makefileに起因するエラーがないこと 
**やったこと** 
- envファイルを明示的に参照するようにしました。（makeした時に失敗したので）

Integration: update makefile

---

api/conf/app_match/utils.py
api/conf/app_match/views.py
api/conf/app_player/utils.py
api/conf/app_tournament/utils.py
api/conf/app_tournament/views.py

**Testの方法**
- コンテナ内で全てのテストに合格すること
- DBとの接続を切ってリクエストを送った時に複雑なエラーページが表示されないこと。（シンプルなJSONレスポンスであること）
**やったこと**
- キャッチできてない例外（DB接続のエラー）がないようにしました。
- try exceptをview関数にまとめました。

Api enhancement error handling

---

static-builder/src/js/features/tournament/Tournament.js

二人の時のトーナメント画面。
優勝者が決まっている時に表示するように

2player tournament

---

static-builder/src/js/components/common/Header.js
static-builder/src/scss/styles.scss

unable header link

---

static-builder/src/js/infrastructures/api/tournamentApi.js
static-builder/src/js/infrastructures/cookie/cookie.js
static-builder/src/js/pages/Home.js
static-builder/src/js/pages/InputAlias.js
static-builder/src/js/pages/Pong.js
static-builder/src/js/pages/Tournament.js

cookieを使って、継続中のトーナメントに戻れるように
終わったらcookieを削除

Return tournament

---

static-builder/src/js/pages/Pong.js

トーナメントへボタンがマッチ終了していないと出ないようにした

fix トーナメントへボタン

---

api/conf/app_match/utils.py

fix sorted

---

reverseproxy/nginx.conf

ref: https://discord.com/channels/1243483887930445865/1243487304841039915/1292088777250045972

ルートパス以外で404が返される問題を修正する

---

docker-compose.yml

fix_error: 引数が誤っていたため修正

---

static-builder/src/js/libs/router.js
static-builder/src/js/pages/Home.js
static-builder/src/js/pages/InputAlias.js

2,4,8以外の無効な人数が入力された時に二人の画面にリダイレクトする処理書きたいけど、いくつか考慮することが必要そうなので別で対応する
https://github.com/user-attachments/assets/521383ae-7d2e-4679-8b34-714bab000345

エイリアス入力画面でページをリフレッシュしても要素が消えないようにする

---

.github/workflows/issue-template-initializer.yml

チケット：#129 
---
- 挿入されるテンプレート
```md
- 
- 
- 
---
```
※レビュワーはランダムに2人アサインされる
- 挿入直後の見た目はこんな感じ

子タスクにissueテンプレートを追加

---

asyncapi.yaml

- ASyncAPIを作成
エンドポイント概要の逐次処理をyml化したものになります。
https://miro.com/app/board/uXjVKDAW9_g=/?openComment=3458764605853849782
- 具体的な通信内容は下記のもの
| ユーザー -> サーバー | サーバー -> ユーザー |
| --- | --- |
| <img width="661" alt="スクリーンショット 2024-11-25 12 18 18" src="https://github.com/user-attachments/assets/269342a6-ac3f-466b-98b1-1178db42cdd5"> |<img width="661" alt="スクリーンショット 2024-11-25 12 19 24" src="https://github.com/user-attachments/assets/c3c8d22f-7d2a-4273-868b-034270c6a325">|
- モックサーバーをたてる
- OpenAPIの変更
下記サイトにてコピペしてみる、どのような形になっているか把握できます。
versionはあえて古いものを使用しているので、アップデートしませんか？みたいなwarningが出るかも。
https://studio.asyncapi.com/
- リモートプレイヤーで大きく変更がある。
送る内容もセキュリティ系も(下記参考)
```yml
security:
- sessionAuth: []
```
- エンドポイントがmatchIdとかでなくて問題がないか。
エンジニアの組織論みたいな本読んでるけど、面白い。

ASyncAPIの作成

---

Makefile
mock-server/Dockerfile
mock-server/async-server/.editorconfig
mock-server/async-server/.eslintrc
mock-server/async-server/.gitignore
mock-server/async-server/Dockerfile
mock-server/async-server/README.md
mock-server/async-server/asyncapi.yaml
mock-server/async-server/config/common.yml
mock-server/async-server/index.html
mock-server/async-server/package-lock.json
mock-server/async-server/package.json
mock-server/async-server/src/api/index.js
mock-server/async-server/src/api/routes.js
mock-server/async-server/src/api/services/api-ws-matches.js
mock-server/async-server/src/lib/asyncapi.js
mock-server/async-server/src/lib/colors.js
mock-server/async-server/src/lib/config.js
mock-server/async-server/src/lib/path.js

基本的にはこの中身を書き換えているだけです。
- `make mock-init`について
`mock-server/`の中にasync-serverディレクトリとmockに必要なものを生成するコマンドです。
AsyncAPI.yamlの更新以外では使わないです。
async-serverディレクトリが存在しているときはerrorになってで終了するようにしています。
- `make mock-start` 
このコマンドでモックサーバーを起動できます。
このdir内は基本的に`@asyncapi/generator@1.9.0`で自動生成されたものになります。
--- 
cliで試してみるなら、下記のコマンドを打ってみると再現できます。
`wscat -c ws://localhost:8080/api/ws/matches`

モックサーバーの作成

---

static-builder/src/js/components/ui/Banner.js
static-builder/src/js/hooks/useBanner.js
static-builder/src/scss/styles.scss

https://github.com/user-attachments/assets/8fb42114-9cf6-4565-bcee-39d40acaf5a6
通知を表示するバナーを追加しました。
使い方はコメントのコードを見てもらうとわかりやすいかもです。
- バナーの左横にアイコンつけて通知の種別わかりやすくする
- 複数のバナーがあったときにずらして表示する
- info の時に一定時間で消すようにする
これはやってもいいかもしれない。やるとしても別PR。

add floating banner

---

asyncapi.yaml

Fixes #151
ほとんど変わってませんが、、詳細はissueを確認ください

AsyncAPIの修正 #151

---

openapi.yaml

Fixes #153
詳細は上記issueを確認してください！
https://editor.swagger.io/ に貼り付けると見やすい。

OpenAPI.yamlの更新（Simple対戦用の追加）

---

docker-compose.local.yml
docker-compose.yml
mock-server/async-server/src/api/services/api-ws-matches.js
static-builder/src/js/pages/Pong.js
static-builder/src/js/pages/Tournament.js
static-builder/src/js/test/pong.js

詳細はチケットを確認してください！
https://github.com/user-attachments/assets/73dd5ef7-f01c-4170-abeb-2502907a9c67
確認方法
```
make local
make mock-start
```
これで、一応遊べるはずです！
分からんかったら聞いてください！

ssp(server side pong) front

---

api/Dockerfile
api/conf/app_user/models.py
api/dev/settings.py
docker-compose.local.yml

#166 と #168 の依存関係をなくすために、先にUsersモデルの作成だけ切り出してmainにmergeしたいです。
ビルドできたらOKですかね。

Usermodelの作成

---

api/conf/project/urls.py
docker-compose.local.yml
docker-compose.yml

/health/を作成してそこでヘルスチェックをする様に変更しました

fix api health check

---

static-builder/biome.json
static-builder/src/js/libs/router.js

ごめんなさい。#175 プルリクをクローズしちゃいました。。
状態が変わっていないことを確認してApproveお願いしますm(_ _)m

Routing with path parameter

---

static-builder/src/js/pages/TournamentsBracket.js

4人対戦の時のずれをなおす

---

api/conf/app_friend/views.py
api/conf/app_user/tests.py
api/conf/app_user/utils.py
api/conf/app_user/views.py

Fixes #226
認証情報からUSERのidを取得する関数がありましたが、それを更新してUSERオブジェクトを取得する関数に変更しました。
- モデルに対するテストケースに合格することを確認してください。`cd api`して`make`を行いコンテナを起動してください。`docker exec -it dev-api bash`でコンテナに入り、`test`を行ってください。テストに合格するはずです。
ルートディレクトリでのmakeは失敗しないはずです。
ただし、ローカルのシンプル対戦、ユーザーの新規登録しかできません。

認証情報からUSERSを取得する関数

---

static-builder/src/js/main.js
static-builder/src/js/pages/Home.js

Fixes #228
ルートディレクトリで``make``して、Home画面の表示がmiro（画面イメージ）と同じこと、および、main.js, home.jsでルーティング先のURIがmiro（画面遷移図）と同じことを確認してください

ホーム画面を作ってURLをセットする

---

Makefile

開発用にelk関連を起動しないように変更

---

.github/workflows/django-tests.yml
.github/workflows/issue-template-initializer.yml
api/Makefile

- apiに移動して、make testでテストが走るようにする
- PRを作成したときに、github actionsで自動でテストが走るようにする

djangoのテストを追加

---

api/conf/room/utils.py

Fixes #277
小さな変更なんですが、後ろに続く実装が影響を受けてるので切り出してプルリクします　@kaaaaakun

roomのKeyのシンタックスを変更する

---

Makefile

makeできるようにする

---

.github/workflows/Integration-test-make-local.yml
.github/workflows/Integration-test-make.yml
docker-compose.local.yml

make / make local のテストを追加

---

static-builder/src/js/hooks/useTournamentDetails.js
static-builder/src/js/pages/TournamentWaitBegin.js

・http://localhost/remote/tournament/{tournament_id}
のtournament_idが不正な場合にエラーが出るように修正
・ 残り何人待っているのかをわかりやすくした
- トーナメント実施に必要な人数が揃った時の処理
- 人数が揃った時にはトーナメント表を表示するため、細かいことは置いておいた

use banner

---

api/conf/user/utils.py

UserProfile画面での勝敗がおかしい

---

api/conf/room/consumers.py
api/conf/user/utils.py
api/conf/utils/blockchain_controller.py
static-builder/src/js/pages/UserProfile.js

fix: blcに接続・デザイン変更
